// app/javascript/vue/components/Channels.vue
<template>
  <div>
    <h2>Channels</h2>

    <router-link
      :to="'/channel/' + channel"
      class="channel"
      v-for="channel in channels"
      v-bind:class="{selected: (channel == currentChannel)}"
      >
      # {{channel}}
    </router-link>
  </div>
</template>

<script>
  import { mapGetters } from 'vuex'

  export default {
    computed: {
      ...mapGetters({
        channels: 'allChannels',
        currentChannel: 'currentChannel',
      })
    },
  }
</script>

// app/javascript/react/components/Channels.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import { connect } from 'react-redux'

class Channels extends React.Component {
  render() {
    return (
      <div>
        <h2>Channels</h2>

        {this.props.channels.map((channel, idx) => {
          return (
            <Link
              to={'/channel/' + channel}
              key={idx}
              className={"channel " + (channel == this.props.currentChannel ? 'selected' : '')}
              >
              # {channel}
            </Link>
          )
        })}
      </div>
    )
  }
}

const mapStateToProps = state => ({
  channels: state.channels.all,
  currentChannel: state.channels.current
})

export default connect(mapStateToProps, {})(Channels)
