// app/javascript/react/components/UsersOnline.jsx
import React from 'react'
import { connect } from 'react-redux'

class UsersOnline extends React.Component {
  render() {
    return (
      <div>
        <h2>People</h2>

        {this.props.users.online.map((user, idx) => {
          return (
            <div className="user" key={idx}>
              {user.nickname}
            </div>
          )
        })}
      </div>
    )
  }
}

const mapStateToProps = state => ({
  users: state.users
})

export default connect(mapStateToProps, {})(UsersOnline)

// app/javascript/vue/components/UsersOnline.vue
<template>
  <div>
    <h2>People</h2>

    <div class="user" v-for="user in usersOnline">
      {{user.nickname}}
    </div>
  </div>
</template>

<script>
  import { mapGetters } from 'vuex'

  export default {
    computed: {
      ...mapGetters({
        usersOnline: 'usersOnline'
      })
    },
  }
</script>
